### ISSUE TITLE
forceConfirm option not working

### ISSUE THREAD

**Issue by appshore** [FineUploader/react-fine-uploader#109]
I'm using Gallery (1.0.0-rc1)

The option forceConfirm doesn't seem to work. No prompt appears. 

in options
```
            deleteFile: {
                enabled: true,
                forceConfirm: true,
                endpoint: '/api/v1/upload'
            },
```

**Comment by rnicholus** [comment]
That's correct. `forceConfirm` is a Fine Uploader UI option. With React Fine Uploader, you can contribute an [`onSubmitDelete` callback handler](https://docs.fineuploader.com/branch/master/api/events.html#submitDelete), which allows a `Promise` to be returned. You can prompt the user and `reject()` the `Promise` if they do not confirm.
