### ISSUE TITLE
Get submitted files

### ISSUE THREAD

**Issue by khoshbin** [FineUploader/react-fine-uploader#114]
Hi
 Excuse me ,I am new to react-fine-uploader and I couldn't find my answer in your documents.My question is very basic: When using gallary component in a form, how is it possible to get list of uuid , size and name of successful submited files? how we can find out if there was any error with file uploading to prevent whole form submission?

Thanks

**Comment by rnicholus** [comment]
Use the Fine Uploader API: [`uploader.methods.getUploads()`](https://docs.fineuploader.com/branch/master/api/methods.html#getUploads).
