### ISSUE TITLE
Delete button refreshes the page

### ISSUE THREAD

**Issue by khoshbin** [FineUploader/react-fine-uploader#120]
Hi
  It seems that after uploading ,delete button refreshes the page and after refresh, react-fine-uploader lose its state.

Thanks

**Comment by rnicholus** [comment]
Guessing you have the component wrapped in a form. Type=button needs to be added to the source code

**Comment by khoshbin** [comment]
Thank you Ray!Yes,Literally I had used it inside a form. I added type:'button in delete-button.js line 93
Don't you think that it is better to be like an editable property?

**Comment by rnicholus** [comment]
no - it should always have a `type` attribute w/ a value of `button`. Please open a PR.
