### ISSUE TITLE
Exposing callback props instead of endpoint

### ISSUE THREAD

**Issue by oyeanuj** [FineUploader/react-fine-uploader#121]
Hey @rnicholus! While trying to implement your excellent project in a React-Redux project, I have found myself wishing for a different way to make the API requests. Currently, the endpoints are exposed to the `fine-uploader` object and then different components make a call to those endpoints. 

I imagine, most React apps (especially those which are using Redux, Mobx, etc) will already have their own way of making those requests - all configured, with middleware, optimizations, organization. They are usually tied with actions, and reducers aimed at keeping the state in one place. And using this component means to bypass those for file management requests.

What do you think about instead exposing props to which a user provides a function? 

For example, the `DeleteButton` setup is something like this now:
```jsx
const uploader = new FineUploader({
   options: {
      deleteFile: {
         enabled: true,
         endpoint: 'my/delete/endpoint'
      },
      request: {
         endpoint: 'my/upload/endpoint'
      }
   }
})
//.... component code and then the render function like this:
return <DeleteButton id={ id } uploader={ uploader } />
```

Instead, my proposal (which feels more conventional React) would be like this -
```jsx
return (
  <DeleteButton
    id = {id}
    deleteFile = {this.functionThatHandlesDelete}
    enableDelete
  />
```

This would mean that the uploader object is either initialized by the core code, or the developer initializes it without the endpoints and passes it through. 

I am sure you had your reasons to implement how it is, but I just wanted to put out the idea out there incase it resonates.

Thanks!

**Comment by rnicholus** [comment]
What does `functionThatHandlesDelete` look like, for example?

**Comment by oyeanuj** [comment]
@rnicholus The function would call the corresponding actions in Redux/Mobx etc, which themselves would make the XHR calls. Additionally, it gives the users the flexibility to change states, perform any other operation and even affect change in other parts of the application (via Redux/Mobx and the likes).

**Comment by rnicholus** [comment]
I really don't see how this will work. If your code, in this case, sends the request to delete a file, you will also need to update internal fine uploader state with the result. And what about uploading files where many requests are sent? Complexity increases dramatically when dealing with S3 or Azure. If your plan is to make all of the requests yourself, then I'm not sure why you would want to use fine uploader in the first place. React Fine Uploader simply wraps the core library in a React based UI. What you're suggesting, for the most part, replaces the core library too as far as I can tell. Or, at the very least, puts a tremendous amount of complexity and responsibility on your code, something that fine uploader was built to handle itself.

**Comment by rnicholus** [comment]
And I'm not sure why you can't make use of the existing event system to track state or perform other operations as or when needed.

**Comment by rnicholus** [comment]
closing as I haven't heard back in a while
