### ISSUE TITLE
DeleteButton not rendered when using addInitialFiles() 

### ISSUE THREAD

**Issue by kernow** [FineUploader/react-fine-uploader#128]
I'm having trouble getting the DeleteButton component to work with files loaded using `addInitialFiles()`. I think I've worked out what the issue is but I don't know how to resolve the problem, it may be the way I'm using the components rather than any issue with react-fine-uplaoder.

I'm using the low level components to render a `<Thumbnail />` and a `<DeleteButton />`  component for files added using `addInitialFiles()`. The thumbnail renders ok, and the DeleteButton is generated but the `deletable` state of the `DeleteButton` is set to false which I believe is due to the order of the `statusChange` callbacks.

Here the pertinent sections of my code:

````javascript
componentDidMount() {
  const that = this;
  this.state.uploader.on('statusChange', (id, oldStatus, newStatus) => {
    if (oldStatus === null && newStatus === 'upload successful') {
      // The file was added using addInitialFiles
      that.setState({ files: [{ id, fromServer: true }] });
    } 
  // load the initial files
  this.addInitialFiles();
}

addInitialFiles() {
  this.state.uploader.methods.addInitialFiles(this.props.logos);
}

thumbnail() {
  return (
    this.state.files.map(file => (
      <div key={file.id}>
        <Thumbnail id={file.id} uploader={this.state.uploader} fromServer={file.fromServer} />
        <DeleteButton
          id={file.id}
          uploader={this.state.uploader}
        >
          <i className="fa fa-trash-o" />
        </DeleteButton>
      </div>
      ))
  );
}

render() {
  return (
    <div>
        { this.thumbnail() }
    </div>
  );
}
````

So after my component is mounded I setup a listener that add the file to the `files` state (I am only working with 1 file in this component), it then loads the initial file defined in the `logos` prop. In the render function I'm just looping through the files and rendering a thumb and delete button for each of them.

When a file is added using `addInitialFiles` both components are rendered, but the `DeleteButton` does not show anything as the `deletable` state is set to false. Looking into the `DeleteButton` component code I can see that it sets up it own event listener for `onStatusChange` and will set `deletable` to true if the status is `UPLOAD_SUCCESSFUL`. I believe the trouble is that the `onStatusChange` callback is happening when the file is added using `addInitialFiles` but at this point my code has not rendered the delete button as it is listening to the same event. So when the delete button is rendered the `deletable` status is never changes from false as no more events are fired for this file.

Should I be coding my component differently to avoid this problem? Or is this an issue that needs to be worked around or resolved within react-fine-uploader? I wasn't able to see any way to re-trigger the `onStatusChange` event so that the `DeleteButton` could pick up the correct status of the file.

Thanks

**Comment by rnicholus** [comment]
Not exactly sure what is causing your issue, and I'm afraid I don't have the time to give this a proper investigation. If you find an issue in the code, please do open a PR w/ tests. Thanks.

**Comment by mladen107** [comment]
I have exactly the same issue.

**Comment by kernow** [comment]
@mladen107 I found it was less work to build my own file uploader and not use FineUploader at all. The File API is really easy to work with if you don't need to support IE9 or older. React + Axios + File API is all I'm using and I can now get something that works exactly as I want to without having to jump through hoops.

**Comment by rnicholus** [comment]
...unless of course you want to upload directly to S3, or Azure, or generate scaled versions of images, or maximize throughput using concurrent chunking, etc.

**Comment by rnicholus** [comment]
True, if you're building something small for a small userbase without any need for advanced features, you can do it yourself. But this library is not built for that. And why would it?

**Comment by mladen107** [comment]
There is major issue with this library since it only listens to changes on "statusChange" but it doesn't take into account initial state of uploader... Authors didn't take in consideration that `uploader.methods.addInitialFiles` could be called before the Gallery (this is not limited to Gallery) has been constructed.

I will try to make PR.

**Comment by rnicholus** [comment]
Thanks @mladen107. This is how free open source projects survive, by users like yourself who contribute patches and time. Let me know if you have questions or problems patching this. Ideally, the patch will include tests as well to verify and document the change.
