### ISSUE TITLE
No thumbnails when file is dropped?

### ISSUE THREAD

**Issue by damionmoyer** [FineUploader/react-fine-uploader#130]
When using react-fine-uploader@1.0.2, dropped files do not show a thumbnail, but selected files do. See: https://github.com/damionmoyer/fine-uploader-test

When I run this app and upload a file by drag-n-drop, a generic file icon is displayed, but when I click to invoke a file selection dialog and select the file, then a proper thumbnail is displayed.

Note that I have only attempted this on OS X, but the problem occurs in Chrome, Firefox, and Safari.

Note also that downgrading to react-fine-uploader@0.6.0 fixes the issue.

**Comment by rnicholus** [comment]
Interesting. I've seen a few reports about this recently, but offhand i'm not sure why the dropzone aspect of this would cause the issue you are describing. It may be a little while before I can look closer, so a PR with a fix or more insight into the cause will speed things up.

**Comment by ravanliyski** [comment]
Are there any updates on this?
I am experiencing the same problem

**Comment by rnicholus** [comment]
No updates. If there were updates i would have posted them here.

**Comment by peterdivvito** [comment]
I've just created pull request https://github.com/FineUploader/react-fine-uploader/pull/142 to fix this. It seems bug was introduced in commit 4d912621446370a15bee91b4098fc1e27054ec93

**Comment by rnicholus** [comment]
Fix released as v1.0.3. Thanks @peterdivvito!
