### ISSUE TITLE
Download option question

### ISSUE THREAD

**Issue by mladen107** [FineUploader/react-fine-uploader#136]
I would need to add download button, or for example enable download on title click (if file is uploaded). From what I see it is imposible to do this with current api. I mean I would need to create custom gallery from 0.

I think that you shouldn't limit passing all other props (like `onClick`) to inner components. For example:

```
render() {
        return (
            <span className={ `react-fine-uploader-filename ${this.props.className || ''}` }>
                { this.state.filename }
            </span>
        )
    }
```
should be:

```
render() {
        const {className, ...otherProps} = this.props 
        return (
            <span className={ `react-fine-uploader-filename ${this.props.className || ''}` } {...otherProps}>
                { this.state.filename }
            </span>
        )
    }
```

**Comment by rnicholus** [comment]
Open up a pull request so we can discuss further
