### ISSUE TITLE
Module not found: Error: Can't resolve 'react-addons-css-transition-group'

### ISSUE THREAD

**Issue by zteBill** [FineUploader/react-fine-uploader#138]
Module not found: Error: Can't resolve 'react-addons-css-transition-group' in 'D
:\web_front\react\reactApp\node_modules\react-fine-uploader\gallery'

**Comment by zteBill** [comment]
resolved ：  npm install react-addons-css-transition-group

**Comment by rnicholus** [comment]
See https://github.com/FineUploader/react-fine-uploader/blob/master/package.json#L25

**Comment by hmontes** [comment]
That package is deprecated.

Instead, use https://github.com/reactjs/react-transition-group

Please. Update react fine uploader.

**Comment by rnicholus** [comment]
See #135.

**Comment by hmontes** [comment]
I'm trying to implement the v2 update of react-transition-group (#135 is for v1). Besides, the branch is outdated.

**Comment by rnicholus** [comment]
pull requests welcome
