### ISSUE TITLE
Changing input name 

### ISSUE THREAD

**Issue by morozp** [FineUploader/react-fine-uploader#139]
Hi.
Thank you for your great job.
First time I think that it realy helps in all my cases.
But I can't understand how to  make simple  things in react wrapper than include fine-uploder library.

The first https://docs.fineuploader.com/branch/master/api/options.html#request.inputName.
I tried to set it in 

 FineUploaderTraditional({
	
	options: {
		inputName :'imageFiles',

but it is not worked.

next  to <FileInput  inputName ={'imageFiles'} ...  but it isn't work too.

I lost my hope :(. Please help me.

The second. When I try to add validation of file file doesn't send but, where I can take validation messages and so?

**Comment by rnicholus** [comment]
sorry "it doesn't work" isn't enough information. I'll need a lot more, such as a live or simple reproducible example

**Comment by rnicholus** [comment]
i can re-open this once you're able to provide enough info to help further
