### ISSUE TITLE
How to view/download uploaded files

### ISSUE THREAD

**Issue by nomadus** [FineUploader/react-fine-uploader#146]
This is more a question than an issue. I use Gallery component to upload the files. After file is uploaded how can another user view/download uploaded files? Does Gallery component allow it?

**Comment by rnicholus** [comment]
Sorry, but your question in no way involves this library. If you'd like to allow downloads you are free to do so by rendering anchor links with appropriate hrefs based on your setup

**Comment by nomadus** [comment]
Thanks for the response, as I understood you, I shall have to add list of anchor items with some urls, pointing to the uploaded file. I can see that, but now in my page, I have a list of documents which is inside Gallery component and a new list of the same documents to view those files? Not a best decision from the design point of view.

**Comment by rnicholus** [comment]
wrap each component in an anchor link

**Comment by nomadus** [comment]
Ray, this means that I can't use Gallery component and  I have to use individual components? Could this considered and enhancement request?

**Comment by rnicholus** [comment]
I don't plan on implementing anything further in this library at this point, but I'll be happy to advise anyone working on a pull request to add such an enhancement.

**Comment by nomadus** [comment]
Ok, let me see what could be done.

**Comment by nomadus** [comment]
Hi Ray,
Could you help with the approach? I am planning to add an anchor into the filename component. What is the best way to access the urls of the uploaded files? I was thinking to add additional property, e.g. submittedFiles, which holds a list of files and urls. The urls are obtained from the upload success endpoint. Would this approach work?

**Comment by rnicholus** [comment]
Sounds good to me. Not sure about the name of that property though.
