### ISSUE TITLE
Initial File List feature does not support delete function

### ISSUE THREAD

**Issue by nomadus** [FineUploader/react-fine-uploader#147]
I would like to know, if Initial File List supports delete feature? Currently, I can see only Cancel button when the FineUploader renders with previously uploaded files. 
From my understanding, Cancel just removes a file from the list (including the DOM element); but it does not remove it from the file server.
Having delete function for the initial file list would help to keep the front end list of files in sync with the actual files in the file server.

**Comment by rnicholus** [comment]
looks like this is covered by #134 / #128

**Comment by ltouro** [comment]
Having the same problem here. The delete button is showed for the Initial File List. However, clicking it does not fire any http requests. Just remove the item from the DOM. Will investigate it further and get back to you.

**Comment by ltouro** [comment]
From what I could gather so far, Delete Button for server loaded files does not match the _this.props.id_ with the ID received from the Status Change event raised by the uploader.  Bypassing this check, I could delete the file.

[line 27 on delete-button.jsx](https://github.com/FineUploader/react-fine-uploader/blob/master/src/delete-button.jsx#L27) 
```js
if (id === _this.props.id && !_this._unmounted) {
  ...
}
```
Will continue to investigate why the ID prop does not match.

**Comment by andresdameson** [comment]
I fixed it calling _onStatusChange() when the DeleteButton component is mounted (rendered into the view). The problem is that the button's deletable state isn't recalculated when the files are pulled from the sessiom endpoint.

My problem was with Vue version of FineUploader but I pressume it's the same with the React one:

DeleteButon.vue
` mounted () {
      // Force a status change to recalculate deletable state
      this.uploader.methods.getUploads().map(item =>
        this._onStatusChange(
          item.id,
          item.status,
          item.status
        )
      )
      this.uploader.on('statusChange', this._onStatusChange)
    },
`
I hope it help!
