### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by nomadus** [FineUploader/react-fine-uploader#149]
I am using create-react-app and run npm run analyze to see what is adding most into the final bundle size. I found out that the second largest item is s3.fine-uploader.core.js, which takes 146kb which is 5.7% of the bundle size. In order to use each possible opportunity to reduce the final bundle size, I created the issue to find out if there some ways to do so?
I use import FineUploaderS3 from 'fine-uploader-wrappers/s3';

**Comment by rnicholus** [comment]
I’m open to suggestions. If you have anything specific, please open up a pull request. Currently, I don’t see any issue with the bundle size
