### ISSUE TITLE
FileInput does not care about validation.acceptFiles

### ISSUE THREAD

**Issue by aquinum6** [FineUploader/react-fine-uploader#152]
v: 1.0.6

I found out that even if I set this option to custom uploader created by fine-uploader and supply this to FileInput, file input does not pass attribute 'accept' to input field inside it.

my solution for now:
```
const { uploader } = this.props;
    const accept = get(uploader, 'options.validation.acceptFiles');

    return (
      <FileInput {...this.props} accept={accept}>
```

**Comment by rnicholus** [comment]
I have absolutely no idea why you are setting the accept property like this, or even what this magical “get” method does. What is the actual value you are trying to pass?

**Comment by rnicholus** [comment]
Show me _actusl code_ that demonstrates you setting a _valid_ accept property, along with confirmation in th form of logging that this attribute does not exist on the rendered input in the DOM, and ill reopen. You can learn about the accept attribute at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by aquinum6** [comment]
Sorry for not been clear enough.

uploader is a object of FineUploaderS3 from 'fine-uploader-wrappers/s3';
get is just a lodash get

this is how I'm initing uploader
```
FineUploaderS3({
  options: {
    request: {
      endpoint: createBucket(bucket),
      accessKey,
    },
    signature: {
      endpoint: signature,
      customHeaders: {},
    },
    ...
    validation: {
      sizeLimit: MAX_FILE_SIZE,
      allowedExtensions,
      acceptFiles,
    },
    messages: {
      sizeError: 'File cannot be bigger than 12MB!',
    },
  },
```

and this instance is passed to component which render I described above. I noticed that acceptFiles that is described in docs https://docs.fineuploader.com/branch/master/api/options.html#validation.acceptFiles does not correspond to accept attribute. It might be that I'm doing something wrong.

So to fix this i just set this attribute manually by getting a proper MIMEType from uploader which is passed to component

acceptFiles is set to 'application/pdf' and this value is in uploader just fine (so I can use it). I'm setting that this way because I'm shareing uploder between components in different files (DropZone and ProgressBar)

input does not have accpet attribute.
![selection_002](https://user-images.githubusercontent.com/1774702/31222618-000be9fa-a9c8-11e7-8c27-4370a7f1b7e4.png)

So. No reason to be rude. I rise the issue (or it's not issue) and I'm feel good with myself. What you going to do is up to you. I'm might be a bit short i informations before but I dont have much time during work hours.

**Comment by rnicholus** [comment]
I personally just tested setting the `accept` property on `<FileInput>`, and it worked as expected. There is no issue here. If you are having a problem, the issue lies somewhere in your code.

**Comment by rnicholus** [comment]
...and this is _precisely_ why I asked pointed questions about how you were setting this property, because I suspected your method of setting the value was the cause, and that is most definitely the issue here.

**Comment by aquinum6** [comment]
I think now there is some misunderstanding. You have set `accept` prop on `<FileInput>` something like that:` <FileInput accept='application/pdf' />` ?

What I meant is setting this prop thru uploader object which is anyways passed to `FileInput` anyways. So I'm guessing this method is not supported?

**Comment by rnicholus** [comment]
The supported properties are very clearly documented. There is even an example of setting an accept property in the documentation. Here it is again:

```
#### `<FileInput />`

The `<FileInput />` component allows you to easily render and style an `<input type="file">` element and connect it to a Fine Uploader instance. When any files are selected via the file chooser dialog, they will be submitted directly to the associated Fine Uploder instance.

##### Properties

- `text` - An object that holds properties used to render text for the two possible button states. If you pass a `multiple` boolean attribute, then the `text.selectFiles` value will be rendered (which defaults to "Select Files"). If you do not pass a `multiple` boolean attribute, then the `text.selectFile` value will be rendered instead (which defaults to "Select a File"). This property is ignored if you pass child elements (`children`).

- `uploader` - A Fine Uploader [wrapper class](#wrapper-classes). (required)

For example, suppose you wanted to create a file input button with an upload icon and some text that allows the user to select multiple files, but excludes everything but images in the chooser dialog ([where supported](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Browser_compatibility)). When files are selected by the user, they should be submitted directly to a Fine Uploader traditional endpoint handler:

Note: This assumes you have [the Ionicons CSS file](http://ionicons.com/#cdn) loaded on your page, _and_ that you have an element on your page with an ID of "content".

```javascript
import React from 'react'
import ReactDOM from 'react-dom'

import FileInput from 'react-fine-uploader/file-input'
import FineUploaderTraditional from 'fine-uploader-wrappers'

const uploader = new FineUploaderTraditional({
   options: {
      request: {
         endpoint: 'my/upload/endpoint'
      }
   }
})

const fileInput = (
   <FileInput multiple accept='image/*' uploader={ uploader }>
      <span class="icon ion-upload">Choose Files</span>
   </FileInput>
)

ReactDOM.render(
    fileInput,
    document.getElementById('content')
)
```

You may pass _any_ [standard `<input type="file">` attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) to the `<FileInput />` component.
```

**Comment by rnicholus** [comment]
Take note of this line from the documentation in particular:

> You may pass any standard <input type="file"> attributes to the <FileInput /> component.

**Comment by aquinum6** [comment]
Yes, I have red all of this. So this is not supported. Sorry for bothering you.

**Comment by rnicholus** [comment]
Properties from the uploader are _never_ passed to any component. You can treat the `<FileInput />` is an extended `<input type="file">`. This is not a matter of supported/not supported, simply a matter of using the component as it was intended.
