### ISSUE TITLE
Manual Upload On Button Click

### ISSUE THREAD

**Issue by Arpit1294** [FineUploader/react-fine-uploader#158]
I saw a demo of fine uploader without react where one can first store all file on client side and then manually upload them on to the server using the upload button. 

I want to implement the same logic in react fine uploader.

I am disabling the autoUpload in options object, but I am unable to find a way to manually trigger the upload button. 

Thanks.

**Comment by rnicholus** [comment]
uploader.methods.uploadStoredFiles()

**Comment by Arpit1294** [comment]
In react fine uploader I am not getting any such methods attached to uploader.methods

**Comment by rnicholus** [comment]
please show all of your code

**Comment by DannieYang** [comment]
@rnicholus, how do I resume upload if I have to manually trigger the upload?

Thanks,

**Comment by rnicholus** [comment]
It will auto resume after you start the upload if resume is enabled and a record for the file exists

**Comment by YashKharel19** [comment]
Hello, 
How can I use uploader.method.uploadStoreFiles().
Do you have the documentation for that I want to manually upload the files with custom upload button.Is it Possible to do that? @rnicholus. 
Thanks!
