### ISSUE TITLE
Single File Form Uploads: how to reset the files in the uploader queue?

### ISSUE THREAD

**Issue by arvinsim** [FineUploader/react-fine-uploader#161]
# Goal

I want to be able to upload single files by using a form.

# Environment

## Versions

- "react-fine-uploader": "^1.0.7",
- "fine-uploader": "^5.15.0",
- "fine-uploader-wrappers": "^1.0.1",

## Configuration

```
export const uploaderAttachmentUploader = new FineUploaderS3({
  options: {
    request: {
      endpoint: '...',
      accessKey: '...',
      clockDrift: 500,
      params: {}
    },
    signature: {
      endpoint: '...',
      customHeaders: customHeaders,
      version: 4
    },
    objectProperties: {
      region: '...',
      acl: 'private',
      key: getUuid
    },
    cors: {
      expected: true
    },
    debug: true,
    autoUpload: false,
    multiple: false,
    validation: {
      itemLimit: 1
    }
  }
})
```

## Notes
In the `submit` method callback of the form, I call `uploadStoredFiles()` to manually trigger uploading.

# Problems

The first upload attempt is always successful. But the subsequent uploads have problems.

- When I try to upload again, the previously uploaded is reuploaded.
- When I cancel the first upload and then try to upload again, the first failed attempt is also reuploaded.

# Attempted Diagnosis

It seems to me that the problem is that the upload queue is not being cleared after a successful upload

# Attempted Solutions

I have looked at all the methods in [Fine Uploader documentation](https://docs.fineuploader.com/branch/master/api/methods). It seems to me that `clearStoredFiles()` should be able to clear the files submitted to the uploader. Unfortunately, it doesn't seem to work. 

I also try out the things below

- I called `cancelAll()` in addition to `clearStoredFiles()`
- I called `reset()` instead of `clearStoredFiles()`

None of them work.

# Questions

- How do I properly clear the queue when an upload is done?
- When a file upload is canceled, do I need to manually delete the canceled files?

**Comment by rnicholus** [comment]
Your assumptions here are almost definitely unfounded. What you are describing here would trigger massive numbers of reported issues, if this was actually an issue with the library. You haven’t provided any executable code needed to actually reproduce any of these issues, so I will close this, but am wiling to reopen if you provide runnable examples that demonstrate your issues.

**Comment by arvinsim** [comment]
I am working for a company under NDA so I will provide as much information as that allows.

```
// Component
// handlesubmit is a redux-form method
class UploadAttachmentDialog extends Component {
    render() {
        const { closeDialogDisplay, handleUploadAttachment } = this.props
        return (
            <Dialog
                onClose={closeDialogDisplay}
            >
                <form>
                // ...
                    <Button
                      onClick={handleSubmit(handleUploadAttachment)}
                    <Button 
                </form>
            </Dialog>
        )
    }
}

// Container
export const withUploadAttachmentHandlers = connect(
  // state connectors,
  (dispatch, props) => ({
   closeDialogDisplay: () => {
      const { uploader } = props
      // ...
      uploader.methods.reset()
    },
    handleUploadAttachment: ({ fileDocumentType, file }) => {
      const { uploader } = props 

      // ...

      // Setup Handlers
      const onUploadCompleteHandler = (id, name, response, xhr) => {
        const params = { 
            // parameters
        } 

        // Update some stuff in the backend based
        // on some data and the upload result
        return sendFileUploadData(params)
          .then(response => {
            // Update Status
          })
          .catch(error => {
            // Log Error
          })
          .then(() => {
            // Whether it is a success or fail, I reset.
            uploader.methods.clearStoredFiles
            uploader.methods.reset()
          })
      }

      uploader.off('complete', onUploadCompleteHandler)
      uploader.on('complete', onUploadCompleteHandler)

      // ...

      uploader.methods.uploadStoredFiles()
    }    
  })    
)
```

Let me know if there is anything that is not clear.

**Comment by rnicholus** [comment]
Sorry, I don’t know what I’m looking at or how it relates to your original and confusion questions. Best of luck.
