### ISSUE TITLE
Gallery component doesn't respect hideScaled = true

### ISSUE THREAD

**Issue by dbradleyfl** [FineUploader/react-fine-uploader#163]
Scaled images still show up as thumbnails. Set in config: 
`        scaling: {
          sizes: [
            {name: "thumbnail", maxSize: 200},
            {name: "large", maxSize: 1000}
          ],
          hideScaled: true
        }
`
Easily duplicatable.

**Comment by rnicholus** [comment]
This is a Fine Uploader UI-specific option. If you'd like to see this supported by React Fine Uploader, it will need to be explicitly coded into the library.

**Comment by dbradleyfl** [comment]
I see. I assumed all Fine Uploader UI options were supported in React Fine Uploader - Gallery. I'll use the lower level components to put something custom together. Thanks for the quick response 👍

**Comment by rnicholus** [comment]
Just the opposite - Fine Uploader UI is not even pulled in by React Fine Uploader. It leverages the API (core mode) to put together a completely custom UI for React.
