### ISSUE TITLE
React 16 support?

### ISSUE THREAD

**Issue by TomiS** [FineUploader/react-fine-uploader#166]
Any plans? :)

**Comment by rnicholus** [comment]
such as?

**Comment by TomiS** [comment]
Atm. this lib gives "unmet peer dependency" warning when installed with React 16. Might be enough to just update
https://github.com/FineUploader/react-fine-uploader/blob/master/package.json#L24
to allow version 16 and up.

**Comment by rnicholus** [comment]
It needs to be tested w/ React 16 first. What else are you seeing? What have you tried?

**Comment by TomiS** [comment]
Based on very quick test at least Dropzone seems to work. But I just started updating our app to React 16 so cannot really say anything conclusive yet. I keep my eyes open though.

**Comment by rnicholus** [comment]
I welcome a pull request with this change and information detailing your manual tests. If all looks well, I see no reason to hold up this update. I also want to be sure all dependencies are compatible too.

**Comment by Dog** [comment]
I just tried to bring up this package from scratch with React 16. So far the only trouble I ran into was I needed `yarn add react-transition-group@1.x` because it fails with 1.x.x.

This caused the below Error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by GazzaHazza** [comment]
Any updates on this?

**Comment by rnicholus** [comment]
No, sorry. I'm hoping to find some time in the near future to more consistently maintain this and other FU libraries. There is also the possibility that a second maintainer will join soon.

**Comment by rnicholus** [comment]
Please see https://github.com/FineUploader/react-fine-uploader/pull/171#issuecomment-360960594

**Comment by rnicholus** [comment]
if someone can confirm that https://github.com/Dog/react-fine-uploader/tree/patch-1 fixes all React 16 issues, i'll release a new version.

Please also see #174
