### ISSUE TITLE
Corrupted file and failed status 

### ISSUE THREAD

**Issue by raminahmadi1986** [FineUploader/react-fine-uploader#167]
Hi
I'm using fine uploader in SharePoint Framework , everything seems fine and it uploads the file to the library with SharePoint Rest Api , but it failed and the file is corrupted.
![image](https://user-images.githubusercontent.com/15119083/33944344-1d28298c-e031-11e7-9cd7-dcc0d2fb94b6.png)

**Comment by rnicholus** [comment]
Nothing I can do about that. Would either be a network issue, or some issue with the server.

**Comment by raminahmadi1986** [comment]
but it returns 200

**Comment by rnicholus** [comment]
that's irrelevant
