### ISSUE TITLE
DnD Non-Op in Safari

### ISSUE THREAD

**Issue by SteveGuilford** [FineUploader/react-fine-uploader#168]
Drag and Drop appears to be a non-op w/ Safari. I have a 'Gallery' element that works properly w/ all browsers on all platforms except for Safari on MacOS - naturally!

Upon dragging and dropping an icon is displayed in the Gallery showing a failed upload with a filename of 'misc_data'. When dropping an image, the icon shows a preview properly.

**Comment by rnicholus** [comment]
i have the latest React Fine Uploader integrated into one of my projects, and i'm not seeing any issues. You'll need to provide some information about the actual issue.

**Comment by SteveGuilford** [comment]
I'm on the latest version as well. This issue is only apparent on Mac/Safari.

What other information can I provide? Is there a way to get additional tracing info out of react-find-uploader or its dependents?

**Comment by SteveGuilford** [comment]
BTW..I have a public facing website that you can go to that exhibits the problem.

**Comment by rnicholus** [comment]
I'm not seeing the issue myself on Mac/Safari, so i'll need something specific to reproduce.

**Comment by SteveGuilford** [comment]
If I can impose for a few minutes of your time, you can try things here: http://cloud.asteriondb.com

You'll need to hit the register link and create yourself and account. The system will send you a confirmation email w/ a link that you'll have to access. Upon confirming your account, select The Vault --> Ingest and Catalog. From there you can drag and drop an image file. The system accepts images, videos, PDFs and audio files. Note that 'Select File' works fine.

This is a Cloud based system that I/we at AsterionDB are in the process of building up for commercial release. The system is in beta-test presently so anything you upload will probably be deleted by next week, but, it will suffice for now.

I appreciate any help you can lend. Thanks in advance.

Steve...>>>

**Comment by SteveGuilford** [comment]
Traced it to an improper value for qqfilename. Under Safari, for whatever reason, the request header qqfilename parameter is set to misc_data. The qqfile parameter is set correctly. A simple workaround might seemingly apply and does for small file uploads.  Unfortunately, chunked uploads also sets the value of qqfilename to misc_data while not setting the value for qqfile (at the end of the chunked upload).

**Comment by rnicholus** [comment]
There is nothing in Fine Uploader code that sets this to misc_data. It sounds like this is localized to your integration code, so i'm going to close this.

**Comment by SteveGuilford** [comment]
You're setting your blobs to 'misc_data' all over the place in your code. Searching for 'misc_data' in your code shows 44 hits in 44 files. Turns out formdata-polyfill doesn't like your code. 

Coding around Safari's lack of formData.set is the solution.
