### ISSUE TITLE
How can i change position of upload button and preview thumbnail using react-fine-uploader

### ISSUE THREAD

**Issue by anilljoshi** [FineUploader/react-fine-uploader#172]
fine-uploader.core.js?db7a:952 Uncaught (in promise) TypeError: Cannot read property 'status' of undefined This issue is occure when i use external function in call back
const uploader = new FineUploaderTraditional({
         options: {
            request: {
              endpoint: '/uploads/',
            },
            callbacks: {
              
               onComplete: function(id) {
                  console.log('herer')
                 that.props._handleChange()
                  // you should be able to access this.props here
               }
            },
            deleteFile: {
                enabled: true,
                endpoint: '/uploads/'
            }
         }
      })

**Comment by rnicholus** [comment]
I have no idea what your question is, your code is almost unreadable, and you haven’t even included the failing code in your issue.
