### ISSUE TITLE
Gallery is not working

### ISSUE THREAD

**Issue by MikeBailleul** [FineUploader/react-fine-uploader#174]
Here is what I got what I try to use the sample of the Gallery provided in the README.
`
warning.js?6327:33 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports`

**Comment by rnicholus** [comment]
I can't help if you don't show your code.

**Comment by rnicholus** [comment]
Are you perhaps using React v16?

**Comment by MikeBailleul** [comment]
I haven't provide any code since this is the exact same code provided in the README.

Yes, you're right, I'm using v16... Just realised it isn't supported yet!

**Comment by rnicholus** [comment]
Well, you can verify if a proposed fix actually works then. Please pull down https://github.com/Dog/react-fine-uploader/tree/patch-1 and verify. If it resolves your issue, then I'll release it as a new version.

**Comment by MikeBailleul** [comment]
I just tried, I got another error:

`Uncaught Error: Element ref was specified as a string (dropZone) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).`

**Comment by rnicholus** [comment]
that's definitely an issue on your end

**Comment by rnicholus** [comment]
react-transition-group, unfortunately, is a horrible library that i should have never integrated into React Fine Uploader's `<Gallery>` component, and it's even worse with these incompatibility issues. 

I'm considering a breaking change that will remove react-transition-group entirely but allow you to specify a wrapper for the files list. I haven't considered the best way to do this yet though...

**Comment by rnicholus** [comment]
Also, this version should fix the issue too, i think, but i don't have the time to get React 16 running and I don't want to release this until someone confirms it fixes the issue - https://github.com/Dog/react-fine-uploader/tree/patch-1

**Comment by focux** [comment]
@hackwater This works for me. @rnicholus I tried with that version but it did not work.

**Comment by rnicholus** [comment]
What happened exactly? Because that branch matches @hackwater’s suggestion exactly

**Comment by rnicholus** [comment]
Let's continue this discussion in #171

**Comment by YashKharel19** [comment]
Thank You!
@hackwater  it worked for me too.
