### ISSUE TITLE
Resume upload for manually triggered upload

### ISSUE THREAD

**Issue by DannieYang** [FineUploader/react-fine-uploader#177]
@rnicholus How can I get resume upload working if the upload is triggered manually by calling uploadStoredFiles?

Thanks,

**Comment by rnicholus** [comment]
It will automatically resume if the record exists and resume is enabled

**Comment by DannieYang** [comment]
Hi Ray, @rnicholus. Thanks for your response. If this is the case then it's odd to me.  I can confirm that the resumable file was there, local storage had the resumable file info and resume was enabled. It only works when I enable the auto upload, otherwise it doesn't work. And this is the only change I made. If i manually trigger the upload, upon click the upload button the file (which is the same file as in local storage) I select will be assigned a new uuid which is different that the one associated with the resumable file in the local storage. 

Thanks,
Dannie

**Comment by rnicholus** [comment]
Most likely also merging else is different between the two files then, such as endpoint path. If you can point to a specific bug in Fine Uploader, please open an issue or better yet a PR

**Comment by DannieYang** [comment]
Hi Ray, thanks for you advise. I will double check to see what's difference between autoupload and manual upload. I would dive into the source code when necessary.


Thanks
Dannie

**Comment by DannieYang** [comment]
Hi Ray @rnicholus , I figured that it was the endpoint that was causing the problem. I had it set dynamically by calling the API method after the upload was initialized.

If you don't mind, I'd like to ask if there is way to add an upload button besides the file input in react fine uploader.  

Thanks again,
Dannie
