### ISSUE TITLE
Can't resolve 'fine-uploader/lib/dnd'

### ISSUE THREAD

**Issue by ucil93** [FineUploader/react-fine-uploader#178]
i have an error "Module not found: Can't resolve 'fine-uploader/lib/dnd'" in my project. Can you help?

**Comment by rnicholus** [comment]
Without more information, I cannot

**Comment by ekeyser** [comment]
@ucil93 Just a guess but you probably have to do something like `npm install fine-uploader` or `yarn add fine-uploader`.
