### ISSUE TITLE
How can I include other UI components with each image?

### ISSUE THREAD

**Issue by UmerIftikhar** [FineUploader/react-fine-uploader#181]
Suppose, other than the provided options, I want a toggle switch, a text box and check box for each image. Is it possible? and how?

**Comment by rnicholus** [comment]
I don’t understand your question. Can you provide some code to illustrate? Is there some reason you can’t render these elements alongside each “image”?

**Comment by rnicholus** [comment]
What in the library is preventing this? Seems like you should be able to render these elements with each thumbnail component and position everything with css.
