### ISSUE TITLE
Request header field Cache-Control is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by YashKharel19** [FineUploader/react-fine-uploader#182]
Hi, 
I am using Fine Uploader and when I use endpoint and put my server address there it shows:
Failed to load (serveraddress) :Request header field Cache-Control is not allowed by Access-Control-Allow-Headers in preflight response.
also it shows :
index.js:2178 [Fine Uploader 5.16.0] Error when attempting to parse xhr response text (Unexpected end of JSON input)
my source code is same as the documentation of React Fine Uploader. I replaced the end point with my server address

**Comment by rnicholus** [comment]
This is not a library issue. Rather, it indicates that your server to which Fine Uploader is sending upload requests is on a different domain than that of the page hosting the client (Fine Uploader code). As such, your server must return proper CORS headers and it appears that either it is not doing so, or it is simply not accounting for the a specific header in the response to the browser’s “preflight” CORS request. You can learn more about CORS at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.

**Comment by YashKharel19** [comment]
Hello,
I Found the solution i used Access-Control-Allow-Headers,"*" and it worked.
Thank You.
