### ISSUE TITLE
File is Uploaded Automatically in server but in Client Side It Shows failed 

### ISSUE THREAD

**Issue by YashKharel19** [FineUploader/react-fine-uploader#183]
Hello,
I am trying to upload files from fine Uploader and and It Automatically Uploads in the backend while it shows failed to upload in the browser.Also when I set autoUpload :false I cannot upload it manually how can I upload the files manually as Fine Uploader Demo.

here is my code :
import React, { Component } from 'react';

import FineUploaderTraditional from 'fine-uploader-wrappers';
import Gallery from 'react-fine-uploader';

import 'react-fine-uploader/gallery/gallery.css';

const uploader = new FineUploaderTraditional({
    options: {
        debug: false,
        autoUpload:false,
        chunking: {
            enabled: true
        },
        deleteFile: {
            enabled: true,
            endpoint: 'http://localhost:5000/files'
        },
        request:{
          endpoint:'http://localhost:5000/files'
        },
        // validation: {
        //     allowedExtensions: ['jpeg', 'jpg', 'gif', 'png','tif'],
        // },
        retry: {
            enableAuto: false,
            showButton: false
        },
        resume: {
           enabled: true
        },
        callbacks: {
            onComplete: function(id, name, response) {
                  if (response.success) {
                      alert("UPLOAD SUCCESS");
                  }
                  else {
                      alert("Problem uploading stuff");
                  }
            }
        }
    }
})
export default class UploadComponent extends Component {
    componentWillUpdate(newProps, newState){
        if( newProps.readySubmit ) {
            console.log('InputFineUploader onSubmit', uploader)
            uploader.uploadStoredFiles()
        }
    }
    render() {
        return (
          <div>
              <Gallery uploader={uploader} />
          </div>
        );
    }
}
It is same as the documentation from React Fine Uploader. 
when I set the autoUpload True It shows error in the client side but images get uploaded in the server 
https://imgur.com/a/5Zchb
as shown in the image in the link 
I want to Upload file using the extra upload button so I can bind it with the form I read the documentation from https://docs.fineuploader.com but this did not help.
Can you say what is the issue with my code.
Thanks.

**Comment by rnicholus** [comment]
If the files are reaching their destination successfully but Fine Uploader declares the upload a failure, that indicates your server is not returning a JSON response with a “success” property of `true`. You can also turn off this requirement as of 5.16.0. See https://docs.fineuploader.com/branch/master/api/options.html#request.requireSuccessJson

**Comment by YashKharel19** [comment]
Thank You! It worked :+1:

**Comment by YashKharel19** [comment]
How do I upload it manually ?
