### ISSUE TITLE
How to upload video from fine Uploader.

### ISSUE THREAD

**Issue by YashKharel19** [FineUploader/react-fine-uploader#184]
Hello, 
To upload video,Can we just use allowedExtension mp4 or there are some other criteria?

Thanks!

**Comment by rnicholus** [comment]
You don’t need to do anything to upload videos. But if you want to limit the allowed extensions, you can do so as you’ve described.

**Comment by YashKharel19** [comment]
Hey @rnicholus,
Uploading videos says uploaded successfully but not stored in Server.Also can you help me with the onDeleteComplete events  here is snippet of my code : 
    callbacks: {
            onComplete: function(id, name, response) {
                  if (response.success) {
                      alert("UPLOAD SUCCESS");
                  }
                  else {
                      alert("Problem uploading stuff");
                  }
            },
            onSubmitDelete: function(id) {
                alert("Are You Sure You Wantto delete the item");
            },
            onDeleteComplete: function(id, xhr, isError) {
              if (success) {
                  alert("DELETE SUCCESS");
              }
              else {
                  alert("Problem deleting stuff");
              }
            }
        }
am i doing it correctly ?

**Comment by rnicholus** [comment]
>Uploading videos says uploaded successfully but not stored in Server

I can't help you with that - you'll need to look closer at your server code.

As for your `onDeleteComplete` event, you're referencing a variable that does not exist - `success`. All events are documented at https://docs.fineuploader.com/branch/master/api/events.html. Have a look for more details and examples.
