### ISSUE TITLE
Is it possible to self define chunk size 

### ISSUE THREAD

**Issue by YashKharel19** [FineUploader/react-fine-uploader#189]
I want chunkSize according to speed of internet bandwidth is it possible to self define the chunkSize according to speed  or instead of default 2MB is possible to increase or decrease the chunkSize

**Comment by rnicholus** [comment]
I’m sorry but this does not appear to be a question specifically suited for the React wrapper of Fine Uploader. However, please do review the [chunking.partSize](https://docs.fineuploader.com/branch/master/api/options.html#chunking.partSize) option, which you can contribute a function that is called once per file.

**Comment by YashKharel19** [comment]
Thank You! It worked for me.
