### ISSUE TITLE
How does the request response work in the fine uploader?

### ISSUE THREAD

**Issue by YashKharel19** [FineUploader/react-fine-uploader#190]
What request are sent to server when the files are selected to upload what response does it get back and what are the request response exchange between client and server for each chunk uploaded also what is the final response from the server after file is uploaded.
Any Documentation available or not Fine Uploader Documentation does not clarify it.

**Comment by rnicholus** [comment]
Please only post React Fine Uploader issues in this tracker. If there is something specific missing from the Fine Uploader docs please post an issue in that repo. Thanks.
