### ISSUE TITLE
Is it possible to calculate the fileSize first and divide into chunk accordingly.

### ISSUE THREAD

**Issue by YashKharel19** [FineUploader/react-fine-uploader#194]
Hi,
I want to upload the file by dividing the chunks according to the bandwidth and file size.
I have calculated the bandwidth and now i need to know the file size so i can divide the chunk accordingly.
Can  qqtotalfilesize be read so chunking is done according to it?

**Comment by rnicholus** [comment]
You can set th chunk size dynamically via a chunking.partSize function https://docs.fineuploader.com/branch/master/api/options.html#chunking.partSize

**Comment by YashKharel19** [comment]
I know about chunking.partSize but i want to set chunk according to the file size every time a new file is uploaded.Is it possible to do that ?

**Comment by rnicholus** [comment]
that is called for each file

**Comment by YashKharel19** [comment]
Sorry, I did not get you. I want to set chunk according to the file size (qqtotalfilesize) for each file.
