### ISSUE TITLE
S3 uploader is not working when trying to upload directly to s3 from React via GraphQL server

### ISSUE THREAD

**Issue by vsharan** [FineUploader/react-fine-uploader#196]
```
import React, { Component } from 'react'

import S3FineUploader from 'fine-uploader-wrappers/s3'
import Gallery from 'react-fine-uploader'

// ...or load this specific CSS file using a <link> tag in your document
import 'react-fine-uploader/gallery/gallery.css'

const uploader = new S3FineUploader({
    options: {
        chunking: {
            enabled: true
        },
        deleteFile: {
            enabled: true,
            endpoint: s3 url'
        },
        request: {
            endpoint: "https://bucket.s3.amazonaws.com",
            accessKey: "XXXXXXX"
        },
        retry: {
            enableAuto: true
        },
        signature: {
            method: "PUT",
            endpoint: "using signed url here given from graphQL server"
        }
    }
})


export default class GalleryUploader extends Component {
    constructor(props) {
        super(props)

    }
    componentDidMount() {
        console.log('-------------------onuploader')
        console.log(uploader)
        console.log('-------------------onuploader')
    }
    OnchangeHandler = () => {
        console.log('--------------------------------in handler')
         uploader 
    }

    render() {
        return (
            <Gallery dropzone-disabled={ true }  uploader={uploader} />
    )
    }
}

```

**Comment by rnicholus** [comment]
And by “not working”, you mean...???

**Comment by vsharan** [comment]
Not working mean, I want it to directly uploaded on s3 with signed url given from server. But it fails with signature mismatch. Please guide me through this.

**Comment by vsharan** [comment]
Please provide me proper signature method handling. This is the code area where I have been struggling to upload a file and it has been failing with AWS signature mismatch and a code 403.

**Comment by rnicholus** [comment]
I can’t help you with your signature code because you haven’t posted it here. But take a look at the server-examples repo in this github org for some back ends that sign using both the v3’2 and the v4 method.

**Comment by vsharan** [comment]
I only wanted to know the upload process to s3, step by step. Since I am very close to it. As you can see in below code 
`const uploader = new S3FineUploader({
    options: {
        chunking: {
            enabled: true
        },
        deleteFile: {
            enabled: true,
            endpoint: s3 url'
        },
        request: {
            endpoint: "https://bucket.s3.amazonaws.com",
            accessKey: "XXXXXXX"
        },
        retry: {
            enableAuto: true
        },
        signature: {
            method: "PUT",
            endpoint: "using signed url here given from graphQL server"
        }
    }
})`

But when it goes to AWS, it throws signature mismatch. If you can send me some sample working code on email vinayak.sharan@47billion.com.
