### ISSUE TITLE
How to get pr merged to this project. 

### ISSUE THREAD

**Issue by shivgarg5676** [FineUploader/react-fine-uploader#203]
I have submitted a PR to the project.
[https://github.com/FineUploader/react-fine-uploader/pull/202](https://github.com/FineUploader/react-fine-uploader/pull/202
)
 But body seems to be noticing. What is workflow to submit a PR. Please provide a Contributing.md guide.

**Comment by rnicholus** [comment]
I'm quite busy with my new day job and am struggling to find time to keep my OSS libs up-to-date. I would really appreciate at least one experienced maintainer.

So, without anyone else helping out, I’ll get to PRs when I have time
