### ISSUE TITLE
Render uploading items in outside of fine uploader wrapper

### ISSUE THREAD

**Issue by omidnikrah** [FineUploader/react-fine-uploader#207]
Hi,
I want to when a user uploads some file, fine uploader wrapper hide and display uploading items Instead of that.
How can I render uploading items to another place?

**Comment by rnicholus** [comment]
I don't understand the question. please show what you are trying to do with code

**Comment by omidnikrah** [comment]
@rnicholus 
When you uploading some file, Fine uploader does something like following image: 
![image](https://user-images.githubusercontent.com/8777948/43579276-c210396c-9666-11e8-88b6-1c356386f9f6.png)
But I want to when user uploading some file, Fine uploader display uploading item like following image: 
![artboard](https://user-images.githubusercontent.com/8777948/43579618-f639e85e-9667-11e8-9547-7cf6316ab0e1.jpg)
I don't know how I can do that with Fine Uploader.

**Comment by rnicholus** [comment]
Just as you would with any other react components, you can arrange and combine all of the components in this library to suit whatever layout you require. See the implementation of the gallery component for inspiration.
