### ISSUE TITLE
Thumbnail for video files

### ISSUE THREAD

**Issue by omidnikrah** [FineUploader/react-fine-uploader#210]
Hi, I'm using `Thumbnail` component to display the thumbnail of the file but for the video file, doesn't display video thumbnail. why?

**Comment by rnicholus** [comment]
Thumbnail is for images, not videos

**Comment by omidnikrah** [comment]
But how I can display a thumbnail for videos? Is there anyway?

**Comment by rnicholus** [comment]
This should provide some guidance https://github.com/rnicholus/frame-grab.js
