### ISSUE TITLE
Store endpoint address with file data in localStorage

### ISSUE THREAD

**Issue by omidnikrah** [FineUploader/react-fine-uploader#212]
Hi, When I pause or stop uploading a file, that file stored in localStorage and in next time when I uploading that's file again, FineUploader read that from localStorage.
Now I want to store `Endpoint` address in localStorage to in next time resume uploading file with stored Endpoint.
Can I do that?

**Comment by rnicholus** [comment]
No. Localstorage space is far too small to reliably store files.

**Comment by omidnikrah** [comment]
But now, store file name and id in localStorage. And I need to store Endpoint address because I have many Endpoint address!

**Comment by rnicholus** [comment]
How would storing the file name be useful? How would you retrieve the file later?

**Comment by omidnikrah** [comment]
When I uploading some file and while uploading, refresh the page, FineUploader store the file info in localStorage and in next time for the same file, continue uploading.
But my problem is, We have many Endpoint addresses and in page load, I set Endpoint address. But maybe One file use Endpoint 1 for upload and after refresh, for continue upload in next time I want to set Endpoint 1 for that file.

**Comment by omidnikrah** [comment]
Now, I have uploaded a file and while uploading I refresh the page and after that in my local storage following items stored!
![image](https://user-images.githubusercontent.com/8777948/44296525-ff508180-a2d5-11e8-8776-ee1194957a01.png)
