### ISSUE TITLE
Detect the last file in multiple select

### ISSUE THREAD

**Issue by omidnikrah** [FineUploader/react-fine-uploader#215]
Hi, I want to detect the last file in multiple select. I call an API per file on submit and I want to detect the last item to display a message.
Previously I wrote the following code but it's wrong because ID is not a number to check with the length of files.
```
UploaderConfig.on('submitted', (id : any) => {
  const uploadLength = UploaderConfig.methods.getUploads('SUBMITTING').length;

  if (id+1 === uploadLength) {
    alert('The last file')
  }
});
```
How can I detect the last file?

**Comment by rnicholus** [comment]
Why do you want to do this?

**Comment by omidnikrah** [comment]
I want to call API after submitting all file and I need to detect the last item to call API.

**Comment by omidnikrah** [comment]
Can you help me?

**Comment by rnicholus** [comment]
I suggest monitoring the statusChanged event, and checking the results of getUploads until there all files are submitted. see the docs for more details
