### ISSUE TITLE
Chunk size mismatch error in safari

### ISSUE THREAD

**Issue by omidnikrah** [FineUploader/react-fine-uploader#216]
Hi, When I uploading the file in safari, Fineuploader show me the following error.
<img width="453" alt="screen shot 2018-08-25 at 11 03 12 am" src="https://user-images.githubusercontent.com/8777948/44615909-3f75ae00-a85a-11e8-8cd1-4ed4e066e39d.png">

**Comment by rnicholus** [comment]
No idea
