### ISSUE TITLE
Resume uploading item after pause

### ISSUE THREAD

**Issue by omidnikrah** [FineUploader/react-fine-uploader#217]
In `onResume` event, I pause the uploading item and after that call an API and check chunk data and after that, I want to resume the uploading item but I don't find any resume method!
I use `continueUpload` method, but this changed status of the file to `queue`.
I wrote the following codes:

```
UploaderConfig.on('onResume', (id, name, chunkData, customResumeData) => {
    UploaderConfig.methods.pauseUpload(id);
    axios.get(`https://api.example.com`).then((response) => {
      // Here I need the resume method!
    });
  }
})
```

**Comment by rnicholus** [comment]
Please show ALL of your code.

**Comment by omidnikrah** [comment]
My file uploader configs?

**Comment by rnicholus** [comment]
Well first off, why are you pausing in the onResume method? That seems odd

**Comment by omidnikrah** [comment]
Because I want to send chunks data to the API and check them with the server and if exist in the server, resume the upload else start uploading the file again

**Comment by rnicholus** [comment]
Sorry, I can’t understand what you’ve written. If the status appears as “queued”, then clearly there are other files in progress and you’ve exhausted your maxConnections limit. Once a spot in the queue has opened your file will upload

**Comment by omidnikrah** [comment]
Can you give me your email address to explain more?
