### ISSUE TITLE
Gallery thumbnails disappear on unmount

### ISSUE THREAD

**Issue by diz00** [FineUploader/react-fine-uploader#218]
I have a multistep form (each step has it's own route). On one of these steps you can upload files (I'm using Gallery component). If you go to the next step and then return back to upload step, there will be no thumbnails for uploaded files. I think it's probably because Gallery gets remounted.

Is there any way to keep thumbnails after remounting (i'm using redux for state management)? 

Many thanks.

**Comment by rnicholus** [comment]
See the initial files list feature - https://docs.fineuploader.com/branch/master/features/session.html
