### ISSUE TITLE
Restart uploading file

### ISSUE THREAD

**Issue by omidnikrah** [FineUploader/react-fine-uploader#219]
Hi, Is there any way to restart uploading an item in FineUploader?

I want to check something with API while uploading the file and if it does not match restart uploading the file.

**Comment by rnicholus** [comment]
What do you mean by “restart” an upload?

**Comment by omidnikrah** [comment]
Start uploading from the first. (For specific ID)

**Comment by rnicholus** [comment]
If a file has already been successfully uploaded, there is no mechanism to re-upload it. Just add the file again

**Comment by omidnikrah** [comment]
No, upload the file not finished. I want to restart that between uploading.

**Comment by omidnikrah** [comment]
I manually add a file with `addFiles` method but the status of the file changed to queue and not uploaded.
Also, I call `uploadStoredFiles` method but not working!
