### ISSUE TITLE
Support for server-rendered thumbnails

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/react-fine-uploader#26]
Add this support to `<Thumbnail />`. It will need to look at the `onComplete` response.

**Comment by gedw99** [comment]
i am using the fine upload golang package:
https://github.com/FineUploader/fineuploader-go-server

Do you know if the API between the golang package and this react component interoperable ?

**Comment by rnicholus** [comment]
The react package is just a UI wrapper around the library, so the http end is unchanged.

**Comment by gedw99** [comment]
awesome. thanks

**Comment by rnicholus** [comment]
Seems related to #51.

**Comment by rnicholus** [comment]
Looks like this can be closed, due to work completed in #77. See the [release notes for v0.6.0](https://github.com/FineUploader/react-fine-uploader/releases/tag/0.6.0) for details.
