### ISSUE TITLE
When can we expect Version 1.0?

### ISSUE THREAD

**Issue by couturecraigj** [FineUploader/react-fine-uploader#45]
Hey you guys... I am really liking this component.  It is nice being able to upload files using AJAX to simplify our form entry process.  When can we expect to be seeing a Version 1.0.  Thanks.

**Comment by rnicholus** [comment]
Is there something in particular missing from 0.1.0? There is no specific date for 1.0, and I will prioritize all existing TODO features (and any new ones) based on communication from users like yourself. 

I am the only developer, and I work on React Fine Uploader (and Fine Uploader) as time allows.

**Comment by couturecraigj** [comment]
Well one thing I noticed with the npm package for instance it is missing the css for some reason and that makes this package hard to even put in staging.  My team can work with it as it is better than most everything else out there that I can see.

**Comment by rnicholus** [comment]
oh, that's definitely a bug. I'll fix that right away and release 0.1.1. Just an oversight with the build script.

**Comment by couturecraigj** [comment]
If you are looking to fix those bug on 0.1.0 then there is another issue where it is still looking for a .jsx when all the files have been converted to .js  Those were the only two bugs I found before getting it up and running (minus needing to add style-loader to my webpack).

**Comment by rnicholus** [comment]
Both bugs are accounted for in #46 and #47. I'm about to release 0.1.1 with these fixes. Can you comfirm them after I release?

**Comment by couturecraigj** [comment]
You mean like install the updated package?  Definitely.

**Comment by couturecraigj** [comment]
Do you want help with this...? I really like this so if I fix some of the issues you have listed while using this maybe it can be mutually beneficial... if you like working by yourself that is fine too.

**Comment by rnicholus** [comment]
I just released 0.1.1 with fixes for #46 and #47. Please let me know if this solves those issues for you.

Please do help any way you can. I certainly welcome any and all help, even something as seemingly simple as reporting issues or describing desired features + workflows. 

If you run into any issues setting up the project for development, please let me know.

**Comment by couturecraigj** [comment]
you got rid of a good chunk as I was getting 4 errors now I am just getting this one

```
Error in ./common/routes/Case/components/BranchListItem.js
Module not found: Error: Cannot resolve module 'react-fine-uploader/components/gallery/index.jsx' in /~~/common/routes/Case/components
 @ ./~~/uploader.js 23:13-72
```

**Comment by couturecraigj** [comment]
My bad... I was working around the issue.

**Comment by couturecraigj** [comment]
It is working great... another thing that may reduce adoption is it is not 'Universal' (iso-morphic) ready as it is looking with a global variable 'window' that may or may not be an easy fix I have not looked into it yet.

**Comment by rnicholus** [comment]
Not sure I understand. Can you expand?

**Comment by couturecraigj** [comment]
If you are familiar with SSR (Server Side Rendering) this is used to deal with browsers that do not support JavaScript and as a result improve SEO (Search Engine Optimization).  I have my application load on the server the initial view if you type in a URL directly into the address bar or hit the refresh button... but when adding react-fine-uploader it gives me an error regarding the window variable is not defined like so.  This is actually created by the fine-uploader package not yours but I am thinking there might be a way to inject a window variable into the module to prevent this fatal error when using SSR.
```
ReferenceError: window is not defined
   at Object.<anonymous> (/~/node_modules/fine-uploader/fine-uploader/?:1:32)
   at Module._compile (module.js:541:32)
   at Module._extensions..js (module.js:550:10)
   at Object.require.extensions.(anonymous function) [as .js] (/~/node_modules/babel-register/lib/node.js:152:7)
   at Module.load (module.js:458:32)
   at tryModuleLoad (module.js:417:12)
   at Function.Module._load (module.js:409:3)
   at Module.require (module.js:468:17)
   at require (internal/module.js:20:19)
   at Object.<anonymous> (/~/node_modules/fine-uploader/lib/core/index.js:3:18)
```

**Comment by rnicholus** [comment]
As you surmised, the underlying Fine Uploader library depends on `window`. If you have some thoughts as to how this can be best fixed, please do let me know, as I'm not using SSR in any of my projects at the moment. 

Also, if you could close this issue and open up one specific to the SSR issue, that would be helpful.

**Comment by couturecraigj** [comment]
I was up trying to figure out how to get this to work... I think I figured it out.  Global variables are difficult to work around but with Webpack require.ensure() there is a way to lazy load this after the page has been loaded.  Here is the long and the short of it.

```
const { Promise } = global

export const asyncLoad = () => {
  return new Promise(resolve => {
    require.ensure([], () => {
      resolve({
        FineUploaderTraditional: require('react-fine-uploader').default,
        Gallery: require('react-fine-uploader/components/gallery').default
      })
    })
  })
}
```

Then where you load the it in the page but I moved in a separate location since I use Redux for managing State and this has its own state.

```
import React from 'react'
import { asyncLoad } from './Uploading'  // Lazy Loaded Image Loader

export default React.createClass ({
  getInitialState: function() {
    return {}
  },
  componentWillMount: function () {
    asyncLoad().then(({ FineUploaderTraditional, Gallery }) => {
      const uploader = new FineUploaderTraditional({
        options: {
          autoUpload: true,
          chunking: {
            enabled: true
          },
          request: {
            endpoint: '/api/v0/upload'
          },
          deleteFile: {
            enabled: true,
            endpoint: '/api/v0/upload'
          },
          callbacks: {
            onComplete: (id, name, response) => {
              console.log(id, name, response)
            }
          }
        }
      })
      this.setState({ uploader, Gallery })
    })
  },
  render: function () {
    const { Gallery, uploader } = this.state
    return (
      <div>
        {!('Gallery' in this.state) && <div>Loading Image Loader</div>}
        {'Gallery' in this.state && <Gallery uploader={uploader} />}
      </div>
    )
  }
})
```

**Comment by rnicholus** [comment]
I'm going to close this as it's gone a bit off-topic. If something else specific needs to be discussed further, please open up a new issue.
