### ISSUE TITLE
Document how to make this work with server-side loading.

### ISSUE THREAD

**Issue by couturecraigj** [FineUploader/react-fine-uploader#49]
#45 told how to make something work with server side rendering can you add that to the documentation?  SSR is becoming more common so it makes sense to tell people how to use this component in case they are implementing SSR.

**Comment by rnicholus** [comment]
I'll need to take some time to look over your proposal and perhaps test it myself before adding it to the documentation. Can you paste your proposal here?

**Comment by couturecraigj** [comment]
This is for webpack specifically but any module loader should work using similar promise based structuring.

```const { Promise } = global

export const asyncLoad = () => {
  return new Promise(resolve => {
    require.ensure([], () => {
      resolve({
        FineUploaderTraditional: require('react-fine-uploader').default,
        Gallery: require('react-fine-uploader/components/gallery').default
      })
    })
  })
}```

```import React from 'react'
import { asyncLoad } from './Uploading'  // Lazy Loaded Image Loader

export default React.createClass ({
  getInitialState: function() {
    return {}
  },
  componentWillMount: function () {
    asyncLoad().then(({ FineUploaderTraditional, Gallery }) => {
      const uploader = new FineUploaderTraditional({
        options: {
          autoUpload: true,
          chunking: {
            enabled: true
          },
          request: {
            endpoint: '/api/v0/upload'
          },
          deleteFile: {
            enabled: true,
            endpoint: '/api/v0/upload'
          },
          callbacks: {
            onComplete: (id, name, response) => {
              console.log(id, name, response)
            }
          }
        }
      })
      this.setState({ uploader, Gallery })
    })
  },
  render: function () {
    const { Gallery, uploader } = this.state
    return (
      <div>
        {!('Gallery' in this.state) && <div>Loading Image Loader</div>}
        {'Gallery' in this.state && <Gallery uploader={uploader} />}
      </div>
    )
  }
})```

**Comment by rnicholus** [comment]
Can you confirm that this exact approach allows you to use React Fine Uploader in a SSR project?

**Comment by couturecraigj** [comment]
Yes,

I used it myself all it does is creates a promise to delay loading it until after the page has fully rendered but the exact layout was initially hard to nail down… this way there is the Global window and document object before loading fine-loader.

Craig Couture

**Comment by couturecraigj** [comment]
Yes,

I used it myself all it does is creates a  `Promise` to delay loading it until after the page has fully rendered but the exact layout was initially hard to nail down… this way there is the Global window and document object before loading fine-loader.

**Comment by oyeanuj** [comment]
I think a simpler fix to make sure it works on SSR projects is to check for the `window`, and `document` object before using it. It will be false on the server and true on the client, so the client won't lose out on any functionality.

**Comment by rnicholus** [comment]
Not sure anything is needed here. If so, please open a PR.
