### ISSUE TITLE
add initial files

### ISSUE THREAD

**Issue by kanasite** [FineUploader/react-fine-uploader#51]
http://docs.fineuploader.com/branch/master/api/options.html#session

the session options seem not working

```
const uploader = new FineUploaderTraditional({
    options: {
        chunking: {
            enabled: true,
            concurrent: {
                enabled: true
            },
        },
        session:{
            endpoint: 'http://localhost:8080/list'
        },
        request: {
            endpoint: 'http://localhost:8080/uploads'
        },
        resume: {
            enabled: true
        },
        retry: {
            enableAuto: true,
            showButton: true
        },
        callbacks: {
            onComplete: (id, name, response) => {
                console.log(id,name,response)
                // handle completed upload
            }
        }
    }
})

<Gallery uploader={ uploader } />
```

**Comment by rnicholus** [comment]
Please explain what "not working" means. What are you seeing in the console? What does the HTTP request sent by Fine Uploader look like? How about the response?

**Comment by kanasite** [comment]
@rnicholus 

`[{"name":"small.mp4", "uuid": "da7276a8-15ca-4150-858e-2048d20e9a37"}]`

**Comment by rnicholus** [comment]
Oh, yes, React Fine Uploader does not currently listen for the response to the session request. Furthermore, there is not a simple way (yet) to generate a `<Gallery />` tile for a non-file (in this case, a file record already stored on the server). 

I haven't given this a lot of thought yet, but I _think_ this feature can be rather easily added to React Fine Uploader simply by listening for `onStatusChange` callbacks/events in `<Gallery />` and focusing on `qq.status.UPLOAD_SUCCESSFUL` statuses. If a file's status comes through as `qq.status.UPLOAD_SUCCESSFUL` and it doesn't yet exist in the gallery, then it is a canned/initial file and should be rendered as s tile.

I'd be happy to offer guidance if you're willing to work on a pull request to add this support.

**Comment by smilejos** [comment]
@rnicholus
I would like to ask one more related question.
I use `addInitialFiles()` to add initial files that items previously uploaded and store all information in database..
http://docs.fineuploader.com/branch/master/features/session.html

```js
let list = [{
    id: 0,
    name: "Lighthouse.jpg",
    size: 561276,
    thumbnailUrl: "htt:/localhos:888/101/77eb5865-ac03-407c-93c5-592b6e9977bd/Lighthouse.jpg",
    uuid: "77eb5865-ac03-407c-93c5-592b6e9977bd"
}, {
    id: 1,
    name: "Penguins.jpg",
    size: 777835,
    thumbnailUrl: "http://localhost:8888/101/99877149-53a2-41ac-bf6a-931c1ec1ff40/Penguins.jpg",
    uuid: "99877149-53a2-41ac-bf6a-931c1ec1ff40"
}];

uploader.methods.addInitialFiles(list);
```
But `<Gallery />` can't display thumbnail image. 
I want to use `<Gallery />` to manage previously uploaded image.
Do you have any suggestion ?

**Comment by smilejos** [comment]
By the way,
if i use `<Thumbnail />` to display image.
It will show below svg image for each items.
![image](https://i.imgur.com/cqQsdh9.png)

**Comment by smilejos** [comment]
It seem to `drawThumbnail` method in `<Thumbnail />` only pass three parameter.
```js
// https://github.com/FineUploader/react-fine-uploader/blob/master/src/thumbnail/index.jsx
// line 33-38
this.props.uploader.methods.drawThumbnail(
            this.props.id,
            this.refs.canvas,
            this.props.maxSize
        )
```
Actually, i found out `drawThumbnail` can support more parameters.
if `fromServer` is `null`, `fileOrUrl` will be replaced by `getFile()` function

```js
drawThumbnail: function (fileId, imgOrCanvas, maxSize, fromServer, customResizeFunction)
{
  //....
  if (!fromServer && qq.supportedFeatures.imagePreviews) {
        fileOrUrl = this.getFile(fileId);
  }
  //....
}
```
Therefore, i try to pass extra-parameter `fromServer : true` in `drawThumbnail`
It's workable for me.  :smile: 

But i think it will impact `<Gallery />` component, because of  `<Gallery />` generate image from file directly (not URL). 
This parameter should be managed carefully.

**Comment by rnicholus** [comment]
I'd be happy to offer guidance if you're willing to work on a pull request to add this support.

**Comment by rnicholus** [comment]
Re-opening as it seems this is still needed & there is still work to be done here.

**Comment by truztee** [comment]
I have followed the suggestions on this thread to use onStatusChange event and fromServer parameter to process the initial files, have a look at these changes and let me know if you want me to create a pull request.

[https://github.com/truztee/react-fine-uploader/commit/9370c66da06db75185db7226c44db5f6285b4958](https://github.com/truztee/react-fine-uploader/commit/9370c66da06db75185db7226c44db5f6285b4958)

**Comment by rnicholus** [comment]
Looks good except for a couple things: 

- `Array.prototype.findIndex` is not supported in any version of IE.
- docs will need to be updated, at least for `Thumbnail`.
- updated or new unit test should be considered. 

Please do open up a PR.

**Comment by DonGiulio** [comment]
I'm struggling using this feature and following @smilejos solution, would anyone be so kind and point me to where I could find some docs about this? 

Or maybe someone could give me a hand: My `ImagesUploader` component is as this: 

```
const ImagesUploader = props => {
  const uploader = new FineUploaderTraditional({
    options: {
      debug: true,
      multiple: false,
      request: {
        endpoint: endpoint(props),
        method: method(props)
      },
      validation: {
        itemLimit: 1
      },
      deleteFile: {
        enabled: true,
        endpoint: endpoint(props)
      },
      cors: {
        expected: true
      },
      callbacks: {
        onComplete: (id, name, response) => {
          if (response.success) {
            console.log("UPLOAD SUCCESS");
          } else {
            console.log("problem uploading stuff");
            inspect(response, "response");
          }
        }
      }
    }
  });

  const list = [
    {
      id: 0,
      name: "prima foto",
      size: 561276,
      thumbnailUrl:
        "http://localhost:5000/uploads/item/image/14/533352.jpeg",
      uuid: "77eb5865-ac03-407c-93c5-592b6e9977bd"
    },
    {
      id: 1,
      name: "foto",
      size: 777835,
      thumbnailUrl:
        "http://localhost:5000/uploads/nikele/item/15/185941.jpeg",
      uuid: "99877149-53a2-41ac-bf6a-931c1ec1ff40"
    }
  ];

  uploader.methods.addInitialFiles(list);
  list.forEach(element => {
    // function(fileId, imgOrCanvas, maxSize, fromServer, customResizeFunction)
    uploader.methods.drawThumbnail(element.id, {tagName: "img"}, 300, true);
  });

  return (
    <div id="upload-area">
      <Gallery uploader={uploader} />
    </div>
  );
};
```

It shows the `select files` button, the drop files area, but no thumbnails, the uploads work fine, but I see no thumbnails of the files just uploaded either. 

Thanks in advance :)

**Comment by karianpour** [comment]
I am facing a problem, with this issue. I used this component in a form, and when I open the form I already have the files uploaded data. So I prefer not to send a new request to the server for what I already have in the client.

I used the model that @smilejos is presented above. But it does not work.

```
let list = [{
    id: 0,
    name: "Lighthouse.jpg",
    size: 561276,
    thumbnailUrl: "http:/localhost/101/77eb5865-ac03-407c-93c5-592b6e9977bd/Lighthouse.jpg",
    uuid: "77eb5865-ac03-407c-93c5-592b6e9977bd"
}, {
    id: 1,
    name: "Penguins.jpg",
    size: 777835,
    thumbnailUrl: "http://localhost/101/99877149-53a2-41ac-bf6a-931c1ec1ff40/Penguins.jpg",
    uuid: "99877149-53a2-41ac-bf6a-931c1ec1ff40"
}];

uploader.methods.addInitialFiles(list);

<Gallery uploader={ uploader } />
```

It this supposed to work? I tried to debug `addInitialFiles` method and I found that it goes to `file-uploader.core.js` and fires `this._uploadData.addFile` method. But in the end no thumbnail is rendered.

What am I missing? can some one guide how to do add initial files correctly in react-fine-uploader.

I use the following versions.
```
  "react-fine-uploader": "^1.1.0"
  "fine-uploader": "^5.16.2",
  "fine-uploader-wrappers": "^1.0.1",
```
 Thanks
