### ISSUE TITLE
Resize Before Upload Using Pica Library

### ISSUE THREAD

**Issue by etinif** [FineUploader/react-fine-uploader#53]
Is this currently possible in the react version of fine-uploader? Do I follow the instructions here?http://docs.fineuploader.com/branch/master/features/scaling.html

**Comment by rnicholus** [comment]
Yes, it's possible. Simple specify configuration options as detailed in the doc page you referenced when creating an instance of `FineUploaderS3` or `FineUploader`.

**Comment by etinif** [comment]
Thank you!

**Comment by rnicholus** [comment]
The ES6 `class` wrappers defined in this project are just that - wrappers around the core Fine Uploader library code. With the exception of UI/DOM specific features (since most of those have been re-implemented here using React constructs), all features are available.
