### ISSUE TITLE
Trigger alert message if file extension is invalid

### ISSUE THREAD

**Issue by fabarea** [FineUploader/react-fine-uploader#55]
On the [demo site](http://fineuploader.com/demos.html), Fine Uploader displays an alert message if the file extension does not match the configuration. It would be nice if the react  component could do the same (ie. show an alert message)

**Comment by rnicholus** [comment]
You are free to render an alert message however you choose. Simply observe the relevant callback/event.

**Comment by fabarea** [comment]
Thanks will give it a try

**Comment by rnicholus** [comment]
Sure - I want to avoid making too many assumptions about the application using React Fine Uploader. The simplest way to implement this would be using `alert`, but no one wants to use that in a production app. Short of that, I'd need to either pull in a library to render an alert, or write something myself. In either case, it may not be render appropriately for the enclosing app. I think it's best to just leave this up to integrators like yourself.

**Comment by fabarea** [comment]
Yes, make sense.

Just for the sake of sharing if someone stumbles upon the same need, that worked for me.

```
new FineUploaderTraditional({
    options: {
        ....
        callbacks: {
            onValidate: ({name}) => {
                const parts = name.split('.')
                const extension = parts[parts.length - 1]
                if (!allowedExtensions.includes(extension)) {
                    alert(`${name} has an invalid extension. Valid extension(s): ` + allowedExtensions.join(', '))
                    return false
                }
            }
        }
    }
})
```

**Comment by rnicholus** [comment]
Note that you can also contribute a callback handler at any time using [the wrapper's `on` method](https://github.com/FineUploader/react-fine-uploader#oneventname-handlerfunction-2).
