### ISSUE TITLE
uploader.uploadStoredFiles is not a function

### ISSUE THREAD

**Issue by appshore** [FineUploader/react-fine-uploader#70]
the Fine uploader component works fine in autoUpload:true mode but whenever I call the uploadStoredFiles method to trigger the upload in autoUpload:false mode I got the error: uploader.uploadStoredFiles is not a function. Here the code

```
import React, { Component } from 'react'

import FineUploaderTraditional from 'react-fine-uploader'
import Gallery from 'react-fine-uploader/components/gallery'

const uploader = new FineUploaderTraditional({
    options: {
        autoUpload: false,
        chunking: {
            enabled: false
        },
        deleteFile: {
            enabled: true,
            endpoint: '/upload'
        },
        request: {
            endpoint: '/upload'
        },
        retry: {
            enableAuto: false
        }
    }
})

export default class InputFineUploader extends React.Component {

  constructor(props) {
      super(props)
      this.state = {
          className: '',
          errorMessage: ''
      }
  }

  componentWillUpdate(newProps, newState){
      if( newProps.readySubmit ) {
          console.log('InputFineUploader onSubmit', uploader)
          uploader.uploadStoredFiles()
      }
  }
  render() {
      return (
        <div className={'form-group ' + this.state.className}>
          <label className='control-label' htmlFor={this.props.name}>{this.props.label}</label>
          <span className='text-warning pull-right'>{this.state.errorMessage}</span>
          <Gallery uploader={ uploader } />
        </div>
      )
  }
}
```

**Comment by rnicholus** [comment]
What version of React Fine Uploader are you using?

**Comment by rnicholus** [comment]
My guess is you are using an old version. I would suggest upgrading. Regardless, methods must be accessed via the `methods` property on the upload wrapper instance. More details at https://github.com/FineUploader/fine-uploader-wrappers/blob/master/README.md#methods.

**Comment by appshore** [comment]
Thank You for the quick response. Upload is working fine now.

I upgraded from 0.4.0 to 0.5.0, made some change to import fine-uploader-wrappers instead of react-fine-uploader

My source code was based on this documentation: https://docs.fineuploader.com/branch/master/features/upload-files.html
