### ISSUE TITLE
qquuid or uuid? and batchId

### ISSUE THREAD

**Issue by appshore** [FineUploader/react-fine-uploader#73]
When uploading a file the unique id retrieved from the req.body on the server side (multer) is qquuid. 
When deleting a file it is uuid (in req.params).
The client method getUploads return an uuid. 

Also the batchId (from getUploads) is not available on the server side when a file is uploaded. That could be useful to allow to group all files of a batch in a dedicated folder.

**Comment by rnicholus** [comment]
Not sure what your question/request is, or how this relates directly to this React wrapper. Can you explain a bit more? If you have two entirely separate requests, please open two issues and elaborate on each..
