### ISSUE TITLE
Dropzone element option?

### ISSUE THREAD

**Issue by danielsarin** [FineUploader/react-fine-uploader#78]
Hi,

How is the Dropzone component supposed to be used with the element option? The documentation says it should be a DOM element, and that is what fine uploader expects, but the PropType is expected to be a string. And can a DOM element even be accessed in the render function?

Maybe I just can't figure it out. But if this is a bug, it could be changed to accept a react element or a classname/id of an element.

**Comment by rnicholus** [comment]
When using this React wrapper, you can and should ignore all UI-specific options and API methods from the underlying library. This wrapper library completely replaces the UI code from the underlying Fine Uploader library. 

When you you instantiate an instance of Fine Uploader here, as the documentation illustrates, you're creating an instance of Fine Uploader "core", which does not include any of the built in UI. 

See the [docs for examples and info](https://github.com/FineUploader/react-fine-uploader/blob/master/README.md#dropzone-) on how to use the `<Dropzone />` element by itself.

**Comment by danielsarin** [comment]
Ok thanks. I was not thinking about using any options or methods from fine uploader core, I was just looking at the source code how it works.

I now realized that the element option does work with something like document.body passed as a prop, as mentiond in the docs. But the PropType is still wrong here:

https://github.com/FineUploader/react-fine-uploader/blob/master/src/dropzone.jsx#L8

It gives an error:

Warning: Failed prop type: Invalid prop `element` of type `object` supplied to `DropzoneElement`, expected `string`

So it should be object, and not string.

**Comment by rnicholus** [comment]
Sorry, guess I misunderstood your original question. The PropType should be of type `node` instead of `string`. If you can open up a pull request to fix, that will be helpful. Otherwise I will fix when I get a chance. 

Just curious: why are you using this option instead of wrapping your drop area in the component? Are you looking to make the entire page a drop area, or...?

**Comment by danielsarin** [comment]
Actually I'm not sure if I will be using it, I was just testing different options and use cases.

But I can try to make a pull request.

**Comment by danielsarin** [comment]
I made the pull request https://github.com/FineUploader/react-fine-uploader/pull/79

It should be object, because fine uploader is expecting a DOM node. If the PropType would be node, it would mean a ReactNode, which does not work.

**Comment by rnicholus** [comment]
About to be fixed/released in v0.6.1.
